<div>
    <h2>Contenu contrat</h2>
    <p>
    <?php
        echo 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam elementum, lectus et maximus sollicitudin, augue turpis imperdiet quam, id elementum justo odio finibus ipsum. Nunc tempus metus augue. Integer porta molestie suscipit. Donec mi elit, accumsan vitae nisl in, scelerisque congue lorem. Nam ullamcorper tincidunt pulvinar. Vivamus ac semper nisi, vel consequat dui. Cras eget mollis nunc. Maecenas tempus sapien dui, ut viverra nisi vehicula eget. Ut sollicitudin finibus ornare. Maecenas fermentum gravida nisl ac vehicula. Suspendisse arcu ex, condimentum sit amet mauris a, mollis bibendum arcu. Morbi efficitur mi tortor, in rhoncus ipsum vulputate sit amet. Suspendisse non odio vehicula, luctus libero sit amet, congue ligula. In porta accumsan erat, sed mattis mauris vestibulum et. Nullam vehicula ut magna at congue. Nam efficitur scelerisque justo ac bibendum.

        Praesent et erat scelerisque, sagittis odio in, faucibus odio. Donec tortor sapien, facilisis nec porttitor a, eleifend ac ligula. Mauris ac lectus pulvinar, hendrerit augue sed, dignissim lectus. Praesent vitae volutpat metus. Cras egestas, urna non sollicitudin iaculis, nibh ante luctus urna, quis malesuada leo sem quis dui. Vivamus condimentum aliquam magna. Quisque hendrerit feugiat efficitur. Donec non nulla porttitor, ultricies nibh sed, fringilla massa. Vivamus sem dui, sollicitudin et eros eget, condimentum commodo purus. Donec ultricies dignissim ornare.
        
        Ut quis varius nunc. Pellentesque id augue commodo, pulvinar metus a, cursus purus. Cras scelerisque nisi lorem, sit amet pulvinar sapien pharetra et. Sed eget luctus augue, id dapibus magna. Etiam vel dui dolor. Mauris lectus ipsum, porta at lobortis in, consectetur vel ligula. Pellentesque ut auctor augue, sit amet rutrum nisl. Ut luctus, elit condimentum scelerisque pharetra, elit ligula elementum purus, eu lobortis arcu leo nec mauris. Maecenas pretium hendrerit leo. Donec ex odio, lobortis sit amet pretium porttitor, hendrerit ac enim.
        
        Maecenas egestas dolor fermentum dolor ultricies, ac luctus turpis sodales. Donec at est ut nisl porta ultricies et a metus. Quisque quis consequat neque, ut bibendum nisi. Suspendisse fermentum pellentesque faucibus. Praesent blandit tortor a orci placerat volutpat. Nam tincidunt bibendum quam sed ultricies. Duis vulputate, eros a pharetra mollis, tellus sapien ornare leo, eu mollis urna diam quis tortor. Aenean pellentesque commodo convallis. Sed vitae congue turpis, ut auctor ante.
        
        Phasellus sollicitudin eget nulla id vehicula. In commodo sodales mauris ut iaculis. Phasellus auctor felis lectus, et venenatis dui tristique eu. Nunc metus ligula, varius egestas varius vitae, egestas quis nunc. Suspendisse in dolor eget quam convallis lacinia. Nunc vel tristique erat. Duis nec luctus turpis. Proin euismod erat nisl, quis imperdiet erat sollicitudin a. Sed ac justo velit. Ut turpis elit, faucibus quis elit vel, aliquam tempor quam. Phasellus vel lacinia dolor, quis tincidunt ligula. Duis tempor, risus et commodo convallis, tortor diam tincidunt metus, sit amet egestas nisi ex ut nunc. Sed pellentesque mattis odio a semper. Quisque eleifend vulputate tortor aliquet varius. Etiam porta gravida tellus vel faucibus.'
    ?>
    </p>
</div>